[package]
name = "da"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
procedurals = "0.2.1"
rand = "0.3"
num-complex = "0.1"
ndarray = "0.10"
ndarray-rand = "0.6"
ndarray-linalg = "0.6"
ndarray-odeint = "0.7"
